### ISSUE TITLE
no se adapta a la pantalla, debo bajarle zoom para ver el espacio / columna completa de "Create shifts"

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#10]
![screenshot_1 zoom](https://user-images.githubusercontent.com/38106497/46218176-ffe72980-c311-11e8-9971-764d377ca8d0.png)

**Comment by alesanchezr** [comment]
me puedes dar el tamaño de tu resolucion? nunca pense que podria haber resoluciones tan pequeñas :blush:

Es menos de 600pixeles de alto?

**Comment by alesanchezr** [comment]
@pamelagbl alli quite como 100px de heigh a ver q tal.

**Comment by pamelagbl** [comment]
Listo :) @alesanchezr

**Comment by pamelagbl** [comment]
pero sería bueno trabajar en el responsive,

**Comment by pamelagbl** [comment]
@alesanchezr otra cosa, cuando intentas guardar o publicar la invitación y hay error sucede lo mismo (no se adapta la pantalla) y debo bajarle zoom.

**Comment by alesanchezr** [comment]
Esto se resolvio. El responsive no va para este release.
