### ISSUE TITLE
Shift Offers: No se debería poder eliminar una invitación de trabajo cuando se tenga por lo menos 1 aplicante.

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#12]
Si ya la invitación de trabajo tiene un aplicante pienso que no debería poder eliminarse.

**Comment by alesanchezr** [comment]
Pero las invitaciones son individuales, cada talento tiene una invitacion diferente. A que te refieres con esto?

**Comment by pamelagbl** [comment]
Lo que me refiero es que si ya la invitación de trabajo fue aceptada no se debería poder eliminar @alesanchezr a mi parecer pues

**Comment by alesanchezr** [comment]
Y donde se puede eliminar?

**Comment by pamelagbl** [comment]
En Applicant details. Dice que no se puede rechazar o aceptar una invitación, pero tu le das a la "x" y te elimina o rechaza esa aplicación.
![screenshot_3](https://user-images.githubusercontent.com/38106497/46432509-71611680-c71c-11e8-8ded-2cb189eaf895.png)

**Comment by pamelagbl** [comment]
> Y donde se puede eliminar?
Shift Details
![screenshot_5](https://user-images.githubusercontent.com/38106497/46432767-0b28c380-c71d-11e8-8d5d-19d4da6475ff.png)

**Comment by pamelagbl** [comment]
Si ya hay aplicantes pienso que no debería poder eliminarse...

**Comment by alesanchezr** [comment]
A no lo que pasa es que esto si pasa bastante. Si el shift ya no va se eliminar y punto. Y le mando una notificacion a todos los que habian aplicado o incluso a los que ya habian sido aceptados para comentarles que ese trabajo fue cancelado. 

Capaz en una futura version penalizamos a los empleadores que cancelen muchos shifts, creo que va a ser importante para evitar que los talentos desconfien de JobCore.

Voy a marcar esto com un feature request para una futura version.

**Comment by alesanchezr** [comment]
Cerrado en decremento de #19
