### ISSUE TITLE
Create shift / talent search

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#15]
Estuve creando invitaciones de trabajo y en el proceso tambien asignaba quien calificaba mejor para ese puesto, lo hacía desde mil formas desde agregando al usuario a una lista de favoritos o asignandole directamente pero no me llegaba ninguna invitación de trabajo.

En talent search puedo invitar al usuario X y asignarle el job y ahí si me llegaban las invitaciones de trabajo.

Mi duda es, si son dos procesos igual o deberían de hacer la misma función. Directamente desde el create shift puedes invitar al usuario y en talent o solamente en talent se puede hacer la invitación al usuario, si es así entonces para que está la opción en **Create Shifts**? @alesanchezr

**Comment by alesanchezr** [comment]
Cuando creas el shift se invita masivamente a la gente que cumpla con el criterio establecido, incluso si el employer no conoce a esa persona, en cambio cuando vas a la lista de talentos puedes manualmente invitar a alguien.
