### ISSUE TITLE
Applicant Details: Se puede o no rechazar desde el web client una invitación de trabajo?

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#16]
![screenshot_6](https://user-images.githubusercontent.com/38106497/46432987-aa4dbb00-c71d-11e8-8c8e-4ed04de573e0.png)
Tenía tres invitaciones de trabajo, ya con un usuario que lo había aplicado. Si presiono en el icono "x" lo elimina o rechaza pero en el instructivo dice que no se puede rechazar o aceptar una invitación.

**Comment by alesanchezr** [comment]
@pamelagbl Voy a cerrar este issue entonces.
