### ISSUE TITLE
Applicant Details: Filter Applicant no funciona

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#17]
No se realizar ningún filtro, no se sabe cual es el error...
![screenshot_4](https://user-images.githubusercontent.com/38106497/46433108-044e8080-c71e-11e8-9b19-e0636b639ba2.png)

**Comment by alesanchezr** [comment]
Lo estoy incluyendo en el proximo release.

**Comment by alesanchezr** [comment]
terminado.
