### ISSUE TITLE
Talent Search: Filter Talents no funciona el filtro

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#18]
![screenshot_7](https://user-images.githubusercontent.com/38106497/46433253-60190980-c71e-11e8-8706-1b438ed74e53.png)

**Comment by alesanchezr** [comment]
No lo logro replicar, tienes los pasos? A mi me esta funcionando bien 🤕

**Comment by alesanchezr** [comment]
Terminado.
