### ISSUE TITLE
Create Shitf: New Venue -> Address "There was an error obtaining the location coordinates"

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#21]
Al colocar una de las sugerencias en el campo para añadir la localidad arroja un mensaje de error como en la imagen. 
Occure con direcciones cortas / pocas especificas quizás.
![image](https://user-images.githubusercontent.com/38106497/47099673-2c54de00-d20c-11e8-87f9-b4f0f86dc971.png)

**Comment by pamelagbl** [comment]
creo que no es un bug como tal...

**Comment by alesanchezr** [comment]
Creo q es el api de google maps.
