### ISSUE TITLE
Invite Talents: En la lista desplegable no se visualiza correctamente la hora del shift.

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#23]
No se visualiza correctamente la hora del shift ![screenshot_2](https://user-images.githubusercontent.com/38106497/47578350-8e55c780-d91f-11e8-887b-70f911a1cd7e.png)

Hora correcta del shif ![screenshot_4](https://user-images.githubusercontent.com/38106497/47578352-8f86f480-d91f-11e8-9374-38a4d27ec973.png)

**Comment by alesanchezr** [comment]
ya fue solucionado, se incluirá en `v0.0.15`
