### ISSUE TITLE
Login de usuario - Permisos de usuario: Con mis credenciales de employee puedo entrar en la web de employer

### ISSUE THREAD

**Issue by pamelagbl** [JobCore/employer-web-client#9]
Intento crear invitaciones y me arroja el siguiente error: 
employer: ["This field may not be null."]}
employer: ["This field may not be null."]

**Comment by alesanchezr** [comment]
No logro replicar esto, me pasas un screenshot?

**Comment by pamelagbl** [comment]
@alesanchezr esta listo, ya no ocurre... alguien lo corrigió hmmm

**Comment by alesanchezr** [comment]
jeejje a veces corrigiendo una cosa se corrige otra.
